class Lang {
  static String txt(String key, String? code) {
    Map<String, Map<String, String>> dict = {
      'ko': {
        'slogan': '다같이, 즐겁게, 맛있게',
        'main_title': '한식구', 
        'challenge': '🚀 도전 메뉴',
        'return_main': '홈으로', 
        'save_menu': '메뉴저장', 
        'add_cart': '장보기 추가', 
        'add_manual': '추가로 살것입력',
        'reset_btn': '장보기 목록 초기화',
        'exit_ask': '방을 나가시겠습니까?', 
        'reset_ask': '장보기 메뉴를 초기화하시겠습니까?',
        'save_ask': '새로운 메뉴를 카테고리에 저장하시겠습니까?',
        'cat_delete_all_ask': '모든 카테고리를 삭제하시겠습니까?',
        'cat_delete_single_ask': '이 카테고리를 삭제하시겠습니까?',
        'cat_add_title': '➕ 새 카테고리 추가', 
        'cat_hint': '카테고리 이름 입력 (예: 간식)', 
        'yes': '예', 'no': '아니오', 
        'category': '요리 카테고리 대문',
        'hint_food': '도전 요리 이름 입력 (예: 부대찌개)', 
        'hint_ing': '재료명 (예: 대파)', 
        'hint_amt': '수량 (예: 2개)', 
        'hint_memo': '상대방에게 남길 메모를 입력하세요...', 
        'shop_title': '🛒 장보기 체크리스트', 
        'summary_title': '📋 선택된 요리', 
        'list_title': '🛒 구입할 재료/품목', 
        'empty_msg': '장보기 목록이 비었습니다.',
        'partner_alert': '🔔 당신의 파트너가 장보기를 시작했습니다!', 
        'adjust_tail': '재료', 
        '한식': '한식', '양식': '양식', '중식': '중식', '일식': '일식',
        '지중해식': '지중해식', '남미 요리': '남미 요리', '동남아식': '동남아식', '기타': '기타'
      },
      'en': {
        'slogan': 'Together, Joyfully, Deliciously',
        'main_title': 'Happy Table', 
        'challenge': '🚀 Challenge Menu',
        'return_main': 'Home', 
        'save_menu': 'Save Menu', 
        'add_cart': 'Add to Cart', 
        'add_manual': 'Add Item',
        'reset_btn': 'Clear All Lists',
        'exit_ask': 'Are you sure you want to leave this room?', 
        'reset_ask': 'Do you want to clear the shopping list?',
        'save_ask': 'Would you like to save this new menu to category?',
        'cat_delete_all_ask': 'Delete all categories?',
        'cat_delete_single_ask': 'Delete this category?',
        'cat_add_title': '➕ Add New Category',
        'cat_hint': 'Enter category name (e.g. Dessert)',
        'yes': 'Yes', 'no': 'No', 'category': 'Category Dashboard',
        'hint_food': 'Enter dish name (e.g. Pasta)', 
        'hint_ing': 'Ingredient (e.g. Garlic)', 
        'hint_amt': 'Qty (e.g. 3 cloves)', 
        'hint_memo': 'Type a memo for your partner...', 
        'shop_title': '🛒 Shopping Checklist', 
        'summary_title': '📋 Selected Menu', 
        'list_title': '🛒 Items to Buy', 
        'empty_msg': 'Shopping list is empty.',
        'partner_alert': '🔔 Your partner has started shopping!', 
        'adjust_tail': 'Ingredients', 
        '한식': 'Korean', '양식': 'Western', '중식': 'Chinese', '일식': 'Japanese',
        '지중해식': 'Mediterranean', '남미 요리': 'LatAm', '동남아식': 'SE Asian', '기타': 'Others'
      },
      // 중식(zh) 및 인니어(id) 데이터 생략 (원형 동일 유지)
    };
    return dict[code ?? 'ko']?[key] ?? dict['en']![key]!;
  }
}